"""
The conformance suite: every declarative case, run against the live service.

One pytest test per YAML case, generated by parametrize. A failure therefore
names the case -- `get_missing_device_returns_404` -- rather than reporting that
"the plan failed". Same pattern as project 1.

These are INTEGRATION tests: real HTTP, real service, contract as oracle. The
unit tests in test_validator.py fabricate responses and answer "is the validator
correct?"; these answer "does the running service honour its contract?"
"""

import pathlib

import pytest

from harness.plan import PlanError, load_all_plans, parse_case
from harness.runner import run_case, run_plan, write_summary
from harness.spec import load_contract

PLANS = load_all_plans(pathlib.Path(__file__).resolve().parent / "testplans")


@pytest.mark.parametrize("case", PLANS, ids=lambda c: c.name)
def test_conformance_case(case, transport, contract):
    """
    Run one declarative case against the live service.

    Loaded at import time (not via a fixture) because parametrize needs the list
    before fixtures exist. That is the one place plans have to be read eagerly.
    """
    result = run_case(transport, contract, case)

    assert not result.transport_error, result.transport_error
    assert result.passed, "\n".join(str(v) for v in result.violations)


def test_the_healthy_baseline_is_completely_green(transport, contract, harness_config):
    """
    Every case must pass against a healthy service. Not almost every case.

    A suite carrying permanent known failures is a suite nobody reads: every new
    failure has to be checked against a list of expected ones, and eventually
    someone stops checking. It would also pollute the Day 13 flake detector's
    ground truth, since a case that always fails is not the same as one that
    fails intermittently.
    """
    summary = run_plan(transport, contract, PLANS, harness_config)

    failures = [
        f"{r.name}: " + "; ".join(str(v) for v in r.violations)
        for r in summary.results
        if not r.passed
    ]
    assert not failures, "\n".join(failures)
    assert summary.pass_rate == 100.0


def test_run_summary_is_written_and_self_describing(
    transport, contract, harness_config, tmp_path
):
    """
    The summary must record what it ran against.

    A result you cannot reproduce is an anecdote. Including the config is what
    makes any run reproducible from its own report.
    """
    import json

    summary = run_plan(transport, contract, PLANS, harness_config)
    path = write_summary(summary, tmp_path / "run.json")

    written = json.loads(path.read_text())
    assert written["totals"]["cases"] == len(PLANS)
    assert written["config"]["base_url"] == harness_config.base_url
    assert "seed" in written["config"]
    assert written["totals"]["pass_rate_pct"] == 100.0


# --- plan loading ----------------------------------------------------------


def test_plan_rejects_unknown_case_keys():
    """
    A typo must fail loudly.

    `expect_stauts` silently ignored would leave a case that passes while
    checking nothing -- confidence it has not earned, and wrong in the dangerous
    direction.
    """
    with pytest.raises(PlanError, match="unknown keys"):
        parse_case(
            {"name": "x", "method": "GET", "path": "/health",
             "expect_status": 200, "expect_stauts": 200}
        )


def test_plan_rejects_unknown_expect_keys():
    with pytest.raises(PlanError, match="unknown expect keys"):
        parse_case(
            {"name": "x", "method": "GET", "path": "/health", "expect_status": 200,
             "expect": [{"path": "status", "equalz": "ok"}]}
        )


def test_plan_requires_the_mandatory_keys():
    with pytest.raises(PlanError, match="missing required key"):
        parse_case({"name": "x", "method": "GET", "path": "/health"})


def test_plan_normalises_the_method():
    assert parse_case(
        {"name": "x", "method": "get", "path": "/health", "expect_status": 200}
    ).method == "GET"


def test_plan_knows_which_methods_may_be_retried():
    """
    Day 4's idempotency table, encoded.

    PATCH counts as idempotent only because of the Day 5 decision to allow no-op
    status transitions. Had illegal no-ops returned 409, a retried PATCH would
    fail because the first attempt succeeded.
    """
    def case(method):
        return parse_case(
            {"name": "x", "method": method, "path": "/devices", "expect_status": 200}
        )

    assert case("GET").is_idempotent
    assert case("PUT").is_idempotent
    assert case("DELETE").is_idempotent
    assert case("PATCH").is_idempotent
    assert not case("POST").is_idempotent


def test_every_plan_case_targets_a_declared_endpoint(contract):
    """
    Guards against a case drifting away from the contract.

    A path the contract does not declare produces `unknown_operation`, which is
    the signature of a TEST bug rather than a service bug -- and on Day 14 that
    becomes seeded ground truth. Here it should never happen by accident.
    """
    from harness.validator import find_operation, match_path_template

    orphans = []
    for case in PLANS:
        template = match_path_template(contract, case.path)
        if template is None or find_operation(contract, case.method, template) is None:
            orphans.append(f"{case.name}: {case.method} {case.path}")

    assert not orphans, "cases targeting undeclared endpoints:\n" + "\n".join(orphans)